---
name: Publish a new release on GitHub

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
    tags: '*.*.*'

jobs:
  new-gh-release:
    name: Publish a new GitHub release
    # We publish only if tagged
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5

      - name: create release
        id: create_release
        uses: ncipollo/release-action@bcfe5470707e8832e12347755757cec0eb3c22af
        with:
          draft: false
          prerelease: false
          generateReleaseNotes: true
